# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/ for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  jobs:
    pre_install:
      # Ensure the build directory is clean
      - rm -rf docs/_build || true

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub